### ISSUE TITLE
Search results parsed from HTML fail to match the results visible in the HTML document

### ISSUE THREAD

**Issue by JorgenHookham** [thejeffchen/google-rank-checker#1]
Results in pulled from `keyword_rankings.csv`:

```
judge salary
1. http://www.nytimes.com/2009/01/20/washington/20bar.html
2. http://www.govtech.com/budget-finance/Superior-Court-Wages-Added-to-California-Public-Pay-Website.html
3. https://www.sokanu.com/careers/judge/salary/
4. https://www.sokanu.com/careers/judge/salary/
5. https://www1.salary.com/Judge-Magistrate-salaries.html
6. https://www.glassdoor.com/Salaries/judge-salary-SRCH_KO0,5.htm
7. https://www.indeed.com/salaries/Judge-Salaries
8. https://en.wikipedia.org/wiki/Federal_judge_salaries_in_the_United_States
9. http://www.uscourts.gov/judges-judgeships/judicial-compensation
10. http://www.nytimes.com/2009/01/20/washington/20bar.html
11. http://work.chron.com/annual-salary-judges-9479.html
12. https://www.payscale.com/research/US/Job=Judge%2C_Trial_Court/Salary
13. http://www.ncsc.org/salarytracker
14. https://www.sokanu.com/careers/judge/salary/
```

You can see that these differ from the results displayed in the html file:

![screenshot 2018-03-23 15 42 12](https://user-images.githubusercontent.com/376540/37856278-e81bfb8c-2eb0-11e8-8faa-1ead7f7390f1.png)

It looks like there are a number of results (`document.querySelector('h3.r')`) that are `visibility: hidden`. The first four results in the CSV are invisible, and thereafter the csv appears to be consistent with the html. Do you have any idea what these invisible results are supposed to be? Maybe filtering them out is all that's needed.

![screenshot 2018-03-23 15 44 29](https://user-images.githubusercontent.com/376540/37856373-64139d4e-2eb1-11e8-8df9-1259e4630358.png)

**Comment by thejeffchen** [comment]
Hey Jorgen,

Thanks for noticing this! I took a look and I believe the invisible results are coming from the "related questions" box / "people also ask" box.

![related-questions-screenshot](https://user-images.githubusercontent.com/17417059/37867412-3956e0d0-2f55-11e8-9271-3dc41c201d08.png)

I agree that it is confusing and probably shouldn't be there since those aren't true rankings for a keyword

Looking into the pull request now!
